# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from AddFace import Ui_Form
from DetectFace import Ui_FormDetectFace


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 310, 221, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("access/free-add-user-icon-302-thumb.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btnAddFace = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddFace.setGeometry(QtCore.QRect(210, 550, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAddFace.setFont(font)
        self.btnAddFace.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnAddFace.setObjectName("btnAddFace")
        self.btnAddFace.clicked.connect(self.Open_AddFace)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(770, 300, 221, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("access/1461141.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btnDetectFace = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetectFace.setGeometry(QtCore.QRect(800, 550, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnDetectFace.setFont(font)
        self.btnDetectFace.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnDetectFace.setObjectName("btnDetectFace")
        self.btnDetectFace.clicked.connect(self.Open_DetectFace)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 70, 371, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAddFace.setText(_translate("MainWindow", "Add a new face"))
        self.btnDetectFace.setText(_translate("MainWindow", "Face Detecttion"))
        self.label_3.setText(_translate("MainWindow", "Face detection program"))
    def Open_AddFace (self):
        self.AddFaceWindow = QtWidgets.QMainWindow()
        self.uic1 = Ui_Form()
        self.uic1.setupUi(self.AddFaceWindow)
        self.AddFaceWindow.show()
    def Open_DetectFace (self):
        self.DetectFaceWindow = QtWidgets.QMainWindow()
        self.uic2 = Ui_FormDetectFace()
        self.uic2.setupUi(self.DetectFaceWindow)
        self.DetectFaceWindow.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
